
*global path "C:\Users\chen\OneDrive\Documentos\R\tax_ene2020\tax_2020"
global path "C:\Users\USUARIO\DocsLocales\"
global ecea2 "$path/elasticidad/datos"
global do_files "C:\Users\USUARIO\OneDrive\Documentos\R\tax_ene2020\tax_2020\stata_code\elasticidad"
global ecea2 "$path/elasticidad"
global anios "2016 2018 2020"
*global anios "2018 2020"
global pathout "$path/elasticidad/resultados"
global pathin  "$path/elasticidad/datos"